engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "addon/**"
  - "app/**"
  - "blueprints/**"
  - "**.js"
exclude_paths:
- "tests/*"
